[package]
name = "rusted"
version = "0.1.0"
edition = "2021"


[build-dependencies]
cc="*"

[dependencies]
anyhow = "1.0.95"
crossterm = "0.28.1"
num_cpus = "1.16.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tree-sitter = "0.20.10"
tree-sitter-rust = "0.20.4"
